onflow/service-account

transactions/deployment-allow-list/dec-22/README.md
transactions/deployment-allow-list/dec-22/arguments.json

add giglabs and blocto to deployment allow list

Add members to the deployment allow list

---

templates/capability_pay_rewards.cdc
transactions/pay-rewards/2022/jan-5/README.md
transactions/pay-rewards/2022/jan-5/arguments.json

Added a few folder format changes for the differentiating the new year

Add 2022 jan 5th pay rewards

---

transactions/reset-epoch/2022/apr-7/README.md
transactions/reset-epoch/2022/apr-7/arguments.json

Add reset epoch tx

---

transactions/pay-rewards/2022/jun-15/README.md
transactions/pay-rewards/2022/jun-15/arguments.json
transactions/set-approved-id-list/2022/june-15/README.md
transactions/set-approved-id-list/2022/june-15/arguments.json

adding 6 new access nodes to the approved list

staking rewards transaction for June15th

---

transactions/set-permissionless/jul-5/README.md

switching Peter with Find in the multisign for permissionless contract deployment

---

flow-staking.json
flow.json
transactions/add-keys/2022/jul-27/README.md
transactions/add-keys/2022/jul-27/arguments.json
transactions/pay-rewards/2022/jul-27/README.md
transactions/pay-rewards/2022/jul-27/arguments.json
transactions/set-approved-id-list/2022/july-27/README.md
transactions/set-approved-id-list/2022/july-27/arguments.json

1. Rewards payout
2. Adding Paul and Vishal's entries to flow.json and flow-staking.json
3. Adding Bjarte as a signer to the Staking account.
4. Access Node for Billance

 multi-sign transaction for July 27th

---

transactions/set-approved-id-list/2022/aug-3/README.md
transactions/set-approved-id-list/2022/aug-3/arguments.json
transactions/set-approved-id-list/2022/july-13/README.md
transactions/set-approved-id-list/2022/july-27/README.md

1. Adding an access node for Greenfield one.
2. Fixing an incorrect update - transaction ID of July 27th was incorrectly added to July 13th.

adding Access Node for Greenfield

---

transactions/pay-rewards/2022/aug-3/README.md
transactions/pay-rewards/2022/aug-3/arguments.json
transactions/set-approved-id-list/2022/aug-3/README.md
transactions/set-approved-id-list/2022/aug-3/arguments.json

Flowty just asked me to add another node (as a backup) for their access node.

Adding another access node for flowty.io

---

transactions/pay-rewards/2022/sep-7/README.md
transactions/pay-rewards/2022/sep-7/arguments.json
transactions/set-approved-id-list/2022/sep-7/README.md
transactions/set-approved-id-list/2022/sep-7/arguments.json

1. Rewards payout for Sept 7th
2. Adding 10 node ids to the approved id list

Multi sign transaction for 7th Sept

---

transactions/pay-rewards/2022/sep-14/README.md
transactions/pay-rewards/2022/sep-14/arguments.json
transactions/set-approved-id-list/2022/sep-14/README.md
transactions/set-approved-id-list/2022/sep-14/arguments.json

1. Rewards Transaction for Sept 14th.
2. Transaction to add 2 new node ids

rewards transaction for sept 14th

---

transactions/pay-rewards/2022/nov-23/README.md
transactions/pay-rewards/2022/nov-23/arguments.json
transactions/set-approved-id-list/2022/nov-23/README.md
transactions/set-approved-id-list/2022/nov-23/arguments.json

1. Adding a new node for Taiwan mobile
2. Rewards payout

multi-sign transactions for Nov 23rd.

---

templates/remove_approved_nodes.cdc
transactions/pay-rewards/2022/nov-30/README.md
transactions/pay-rewards/2022/nov-30/arguments.json
transactions/remove-approved-nodes/2022/nov-30/README.md
transactions/remove-approved-nodes/2022/nov-30/arguments.json

1. Rewards payout.
2. Transaction to remove 6 node IDs which have unstaked.

Multi-sign transaction for Nov 30

---

transactions/pay-rewards/2022/dec-28/README.md
transactions/pay-rewards/2022/dec-28/arguments.json

Reducing rewards to 50% for Samsung and T-system Execution node.

rewards payout dec 28

---

transactions/pay-rewards/2023/feb-1/README.md
transactions/pay-rewards/2023/feb-1/arguments.json
transactions/remove-approved-nodes/2023/Feb-01/README.md
transactions/remove-approved-nodes/2023/Feb-01/arguments.json

1. Rewards payout.
2. Removing extra nodes from the approved ID list which are not staked.

Multi-sign for Feb 1st, 2023.

---

transactions/pay-rewards/2023/mar-1/README.md
transactions/pay-rewards/2023/mar-1/arguments.json

March 1st Pay rewards tx
Some leniency was applied for uptime check, due to emergency spork
One node on the slash list.
`3b57e0ee2ece1f1dbefbd868d3eaac63b32a11df5b1a37d231145ea219055dde`

Add march 1st pay rewards tx

---

transactions/pay-rewards/2023/mar-8/README.md
transactions/pay-rewards/2023/mar-8/arguments.json

Slashing for less than 80% up time:
Node ID: 3b57e0ee2ece1f1dbefbd868d3eaac63b32a11df5b1a37d231145ea219055dde (ChainFlow)
Node ID: d98755f4ae8bef3f372889c4d7010ca784ea6da46fdde63d27ee57b2bf5efdd7 (CoinFund)

Pay rewards tx for march 8

---

templates/remove_approved_nodes.cdc
transactions/pay-rewards/2023/apr-5/README.md
transactions/pay-rewards/2023/apr-5/arguments.json
transactions/remove-approved-nodes/2023/apr-05/README.md
transactions/remove-approved-nodes/2023/apr-05/arguments.json
transactions/set-approved-id-list/2023/apr-4/README.md
transactions/set-approved-id-list/2023/apr-4/arguments.json

1. Rewards payout.
2. Removing RIT VN from the approved node ID list.
3. Add a consensus node for BlockDaemon

Multi-sign transactions for April 5th

---

flow-staking.json
flow.json

replacing Justin Barry and Alex Grach with Dmitrii Fotesco and Chris Ackermann from flow.json and flow-staking.json
This should be merged after https://github.com/dapperlabs/terraform/pull/3580/files has been merged, and the new users have been added to the Google KMS as signers

Updating flow.json and flow-staking.json

---

transactions/update-contract/2023/may-3-rewards/upgrade_and_enable_rewards.cdc

Use the epoch admin to enable automatic rewards instead of the staking admin

use epoch admin for auto rewards upgrade transaction

---

transactions/update-contract/2023/july-5-epoch-del/README.md

Updating the readme file on the [original PR ](https://github.com/onflow/service-account/pull/243)

updating readme with steps

---

transactions/reset-epoch/2023/nov-9/README.md
transactions/reset-epoch/2023/nov-9/arguments.json

> $ ./util epochs reset-tx-args --boot-dir genesis-infos-mainnet24
[{"type":"UInt64","value":"100"},{"type":"String","value":"b976876c61579eff5e95af815c78618a"},{"type":"UInt64","value":"0"},{"type":"UInt64","value":"459999"},{"type":"UInt64","value":"482999"}]

reset epoch for mainnet24

---

transactions/remove-approved-nodes/2024/Feb-21/README.md
transactions/remove-approved-nodes/2024/Mar-8/README.md
transactions/remove-approved-nodes/2024/Mar-8/arguments.json

[FLIP GOV-253](https://github.com/onflow/flips/blob/9e619dda789825a2b22f636b95bffada4aac07ae/governance/20240306-removing-decommisioned-verification-node.md)

transaction to implement FLIP GOV-253

---

transactions/update-contract/2024/sep-11-upgrade-staking/README.md

Uses the CLI to upgrade the Staking contract instead of the multisig tool

Use old multisig method for Sep 11th staking upgrade

---

transactions/remove-keys/2024/nov-19/README.md
transactions/slash-rewards/2024/nov-19/Readme.md
transactions/slash-rewards/2024/nov-19/arguments.json

1. Slash rewards.
2. FLIP 310 implementation

Transactions for 19th Nov

---

flow-staking.json
flow.json

Original Setup:
```
dapperlabs_1    = "Kan,Vishal"
dapperlabs_2    = "Layne,Kshitij"
dapperlabs_3    = "Josh,Sean"
```
New Setup:
```
dapperlabs_1    = "Kan,Jan,Jerome"
dapperlabs_2    = "Layne,Vishal"
dapperlabs_3    = "Josh,Sean"
```

Adjusting the keys for Flow foundation as per changes to the GCP setup

---

flow-staking.json
flow.json
transactions/add-keys/2025/README.md
transactions/add-keys/2025/arguments_service_account.json
transactions/add-keys/2025/arguments_staking_account.json

Layne has now setup her GCP account and provided her public key:
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmpsh/Ro7ujmfyIKJ2iAtFP09wDSY
8G13rxXywwow9BOBGEENet46IaEDdSs4WxWrvspQ0nFYPeDrW7BGUxC6ow==
-----END PUBLIC KEY-----
```
$ flow keys decode pem --from-file ~/layne_public_key.pub 
Public Key 		 9a9b21fd1a3bba399fc88289da202d14fd3dc03498f06d77af15f2c30a30f4138118410d7ade3a21a103752b385b15abbeca50d271583de0eb5bb0465310baa3 
Signature Algorithm 	 ECDSA_P256
```

Implementation of FLIP 321 and 326
